export const CLASS_LIST_LOADING = "CLASS_LIST_LOADING"
export const CLASS_LIST_SUCCESS = "CLASS_LIST_SUCCESS"
export const CLASS_LIST_FAILED = "CLASS_LIST_FAILED"
export const CLASS_LIST_EDIT = "CLASS_LIST_EDIT"